### ISSUE TITLE
Still a bunch of error messages when computing measures

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#13]
When executing python3 experiments.py I still get lots of errors from the measurement routines. These are some examples:

1) When computing effectiveGraphResistance I get 

   Error at src/attributes.c:1420: No such attribute, Invalid value 

2) When computing bridgeness I get 

     Edge doesn't exist

3) Some measures seem to have trouble accessing the attributes they expect to find:

percolatedPath 'state'
percolationCentrality 'state'
networkCriticality 'weight'
sensitivity 'weight'
electricalNodalRobustness 'flow'

Have you updated a library at your end and I need to do the same or do we have some other source of incompatibility? Have you been able to execute experiments.py with no measurement errors at your end?

**Comment by valeriavaldes** [comment]
I executed experiments.py and it was only None output, I changed the functions that needed weights, now are set randomly.
