### ISSUE TITLE
A few remaining details

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#14]
for reconstructabilityCoefficient we get the following error:
ufunc 'heaviside' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

we need a None return value for generalizedRobustnessIndex that throws an exception "0.0 cannot be raised to a negative power"

**Comment by valeriavaldes** [comment]
I fixed the errors and run the test without any error

**Comment by satuelisa** [comment]
Thanks; testing it now at my end :)
