### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#15]
We now get these (I suspect that some measures cannot tolerate cycles):

# ERROR measuring circular_ladder_graph 512 compensatedTotalGeographicalGraphDiversity maximum recursion depth exceeded in comparison
# ERROR measuring circular_ladder_graph 512 coveringDegree maximum recursion depth exceeded while calling a Python object
# ERROR measuring circular_ladder_graph 512 coveringIndex maximum recursion depth exceeded while calling a Python object
# ERROR measuring circular_ladder_graph 512 effectiveGeographicalPathDiversity maximum recursion depth exceeded in comparison
# ERROR measuring circular_ladder_graph 512 totalGraphGeographicalDiversity maximum recursion depth exceeded in comparison
# ERROR measuring ladder_graph 512 compensatedTotalGeographicalGraphDiversity maximum recursion depth exceeded in comparison
# ERROR measuring ladder_graph 512 coveringDegree maximum recursion depth exceeded while calling a Python object
# ERROR measuring ladder_graph 512 coveringIndex maximum recursion depth exceeded while calling a Python object
# ERROR measuring ladder_graph 512 effectiveGeographicalPathDiversity maximum recursion depth exceeded in comparison
# ERROR measuring ladder_graph 512 totalGraphGeographicalDiversity maximum recursion depth exceeded in comparison

**Comment by valeriavaldes** [comment]
I fixed the functions that had problems with cycles

**Comment by satuelisa** [comment]
Thanks; I updated my local copy and left the experiments running on screen on my webserver.
Will report back if it spits out any more complaints (probably after Xmas, though).
