### ISSUE TITLE
Getting a division by zero again; the measure needs an exception

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#16]
componentBasedCharacteristics.py", line 75, in randomRobustnessIndex
    return (1/m) * (1/v) * sum
ZeroDivisionError: division by zero

**Comment by satuelisa** [comment]
Just to clarify: please have all measures exit gracefully even if an empty graph or a disconnected one is given as input.

**Comment by valeriavaldes** [comment]
I added an exception to the function
