### ISSUE TITLE
Some measures always output the same value in the experiments

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#17]
When executing the experiment from experiment.py, I observe the following:

resilienceFactor is always zero
kResilienceFactor is always zero
kVertexFailureResilience is always True (?)
dynamicFragility is always one
globalFunctionalityLoss is always zero
sensitivity is always zero
selfSufficiency is always True
fragility is always zero
functionality is always one
functionalityLoss is always zero
geographicalDiversity is always one
kEdgeFailureResilience is always True
reconstructabilityCoefficient is always zero

Are we sure that they are computed correctly and that any default parameter values are set in a reasonable way? If this is indeed the correct behavior, these measures are pretty useless as they cannot tell apart these diverse graphs. Please investigate. I might be calling them wrong, too.

**Comment by valeriavaldes** [comment]
I checked the measures and added random default values, some notes:
selfSuffiency, kEdgeFailureResilience and kVertexFailureResilience always returns boolean
the rest of the functions are computed correctly

**Comment by satuelisa** [comment]
I am not worried about it returning a boolean, I am worried about it always returning true – no measure is very good if it always says true...
