### ISSUE TITLE
Weird stuff is happening now

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#18]
connectivityRobustnessFunction and kResilienceFactor return lists like [(0,), (1,), (2,), (3,), ...] whereas fragmentation returns lists of lists like [[[17, 7, 19, 23, 18, 25, 5, 14, 24, 4, 8, 6, 13, 15, 10, 21, 20, 3, 16, 0, 9, 31, 29, 12, 30, 27, 2], [11, 28, 22, 26]], [[14, 16, 25, 31, 5, 22, 19, 27, 3, 10, 8, 20, 4, 18, 6, 17, 30, 29, 2], [26, 11, 7, 24]], [[19, 1, 5, 16, 18, 27, 29, 26, 13, 24, 2, 3, 7, 10, 17, 8, 15, 21, 31, 6, 9, 0, 4, 14, 22, 11, 20, 30, 28, 23, 12], [25]], ...] – we need something that is either a scalar or that can be averaged over so as to compare the measures. If the proposal of the measure includes no such mechanism, we either propose one or consider the proposal out of scope of this work as it is not comparable with the others. Functions that are _not_ measures but _auxiliary_ functions for measures should be in a file that does not end in **Characterictics.py** for clarity, please.

**Comment by valeriavaldes** [comment]
Sorry about that, the measures are not supposed to return lists, it was a mistake returning lists, the measures computed the value but returned lists, now they return the correct value.
