### ISSUE TITLE
The new measures still produce errors in the experiments

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#20]
namely vertexResilience & edgeResilience, entropy, robustnessMeasureR, and treeness:

elisa@iMac robustness-and-resilience-in-graphs % grep ERROR results_4sec.txt | cut -d ' ' -f 6- | sort | uniq 
edgeResilience zero-size array to reduction operation minimum which has no identity 4
entropy unsupported format string passed to numpy.ndarray.__format__ 0
entropy unsupported format string passed to numpy.ndarray.__format__ 1
entropy unsupported format string passed to numpy.ndarray.__format__ 2
entropy unsupported format string passed to numpy.ndarray.__format__ 3
entropy unsupported format string passed to numpy.ndarray.__format__ 4
entropy unsupported format string passed to numpy.ndarray.__format__ 5
entropy unsupported format string passed to numpy.ndarray.__format__ 6
entropy unsupported format string passed to numpy.ndarray.__format__ 7
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 0
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 1
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 2
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 3
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 4
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 5
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 6
robustnessMeasureR Error at iterators.c:748: Cannot create iterator, invalid vertex id, Invalid vertex id 7
robustnessMeasureR max() arg is an empty sequence 1
robustnessMeasureR max() arg is an empty sequence 4
treeness float division by zero 0
treeness float division by zero 1
treeness float division by zero 2
treeness float division by zero 3
treeness float division by zero 4
treeness float division by zero 5
treeness float division by zero 6
treeness float division by zero 7
vertexResilience zero-size array to reduction operation minimum which has no identity 0
vertexResilience zero-size array to reduction operation minimum which has no identity 1
vertexResilience zero-size array to reduction operation minimum which has no identity 5
vertexResilience zero-size array to reduction operation minimum which has no identity 7

**Comment by valeriavaldes** [comment]
I fixed the metrics, if the errors continue please let me knnow with which graphs it fails
