### ISSUE TITLE
default values for parameters other than the graph itself

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#3]
when computing a characteristic for an input graph, all other parameters except the graph itself should come, whenever possible, with some suggested default value so as to facilitate the experiments on these subroutines

**Comment by valeriavaldes** [comment]
Added default values for most of measurements

**Comment by valeriavaldes** [comment]
There are some measurements that do not have default values, some measurements need functions as a parameter
