### ISSUE TITLE
library usage unclear

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#4]
I need to know which igraph is being used...

from igraph import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

**Comment by valeriavaldes** [comment]
I used igraph 0.7.1, this is the guide that I used for installing https://linuxanteportas.wordpress.com/2016/11/07/installing-the-igraph-package-for-python-3-on-ubuntu-16-04/
