### ISSUE TITLE
separating characteristics from auxiliary routines

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#6]
it is presently hard to tell which routines are characteristics and which are auxiliary subroutines

it might be easiest to put the auxiliary ones in a separate file

also, the ones that need more than the graph as input really, really need to have default values for all the other parameters; if they need a function, for example, make a default function to use in case none was provided

**Comment by valeriavaldes** [comment]
Auxiliary subroutines are now in a separate file.
All functions have a default value, except for preferential perturbation and maximum perturbation score that needs two graphs.
