### ISSUE TITLE
Handling empty lists

### ISSUE THREAD

**Issue by satuelisa** [niclabs/robustness-and-resilience-in-graphs#8]
Please also return None when a list is empty instead of producing a runtime warning:

.../lib/python3.5/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.

**Comment by valeriavaldes** [comment]
I fixed the functions that could return an empty list, in particular, this warning is from numpy when computing a mean, I couldn't delete the warning but I handled it.
